### ISSUE TITLE
Auth: As a user, I should be able to register

### ISSUE THREAD

**Issue by david-tobi-peter** [zurichat/zc_core#163]
PR -  https://github.com/zurichat/zc_core/pull/188

Slack - HOD

Link - https://api.zuri.chat/users/6133d00e0366b6816a0b75c1

The link shows the details of a user created successfully

Another test link which I worked on is a form that accepts details and implements the create user logic is https://api.zuri.chat/usersform from PR -  https://github.com/zurichat/zc_core/pull/238 but not currently live. It has been merged but my team (Newton) is currently experiencing problems with auto deployment probably due to the dev branch we introduced again.

**Comment by samsoft00** [comment]
This issue already exist, please check before you create issues. thank you.

**Comment by markessien** [comment]
Blank result

**Comment by DavidHODs** [comment]
It is a post method sir, the web will return a method 405 result unless
it's tested with postman
