### ISSUE TITLE
[SECURITY] Registration confirmation code exposed on response

### ISSUE THREAD

**Issue by mimidotsuser** [zurichat/zc_core#410]
A request to create a user on the `/users` endpoint returns a verification code on the response.  
This makes email verification pretty useless at the moment as I can register with any email account and get verified easily.

https://github.com/zurichat/zc_core/blob/6d57d932a43d253c6bd46f308a1f669d416e3de5/user/user.go#L97-L99

**Comment by mimidotsuser** [comment]
_I would have loved to create a fix for this but today is my first day interacting with Golang + just discovered this amazing project._

**Comment by Aminujb** [comment]
We are working in a test environment and that is why it has been made so.

**Comment by Aminujb** [comment]
I just told you it's a deliberate action and no we are not turning it off for now.
