### ISSUE TITLE
Organization: Add Application

### ISSUE THREAD

**Issue by Aminujb** [zurichat/zc_core#93]
Provision an operation that adds an application instance for an organization
Endpoint: /organizations/{org_id}/applications		method=POST

**Comment by kinglighthill** [comment]
Live link: https://api.zuri.chat/organizations/6133c5a68006324323416896/plugin
takes json body 
{
    "plugin_id": "6133eaff0366b6816a0b75c6 ",
    "user_id": "6133d3d00366b6816a0b75c5"
}
slackname: KingHolyhill
